[tool.briefcase]
project_name = "OECT App"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/oectapp"
license = "MIT license"
author = 'Sarthak Jariwala'
author_email = "sarthak@example.com"

[tool.briefcase.app.oectapp]
formal_name = "OECT App"
description = "OECT App written in python using Scopefoundry and PyQt5"
icon = "src/oectapp/resources/oectapp"
sources = ['src/oectapp']
requires = [ #pyside2==5.13.0
    'scopefoundry',
    'h5py',
    'pyqt5',
    'qtpy',
    'pyqtgraph',
    'numpy',
    'ipython',
    'qtconsole',
    'git+git://github.com/ScopeFoundry/HW_virtual_function_gen.git'
    ]


[tool.briefcase.app.oectapp.macOS]
requires = []

[tool.briefcase.app.oectapp.linux]
requires = []
system_requires = []

[tool.briefcase.app.oectapp.windows]
requires = []

# Mobile deployments
[tool.briefcase.app.oectapp.iOS]
requires = []

[tool.briefcase.app.oectapp.android]
requires = []
